[package]
name = "rust_sort"
version = "0.1.0"
authors = ["Anish Sharma <aneeshsharma15@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
